name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            touch .env
            echo PORT = ${{ secrets.PORT }} >> .env
            echo DB_PASSWORD = ${{ secrets.DB_PASSWORD }} >> .env
            echo JWT_SECRET_KEY = ${{ secrets.JWT_SECRET_KEY }} >> .env
            echo API_TOKEN = ${{ secrets.API_TOKEN }} >> .env
            echo USER = ${{ secrets.USER }} >> .env
            echo PASSWORD = ${{ secrets.PASSWORD }} >> .env
            echo ACCOUNTID = ${{ secrets.ACCOUNTID }} >> .env
        - run: flyctl deploy --remote-only
  test:
    name: Test App
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
       touch .env
       echo PORT = ${{ secrets.PORT }} >> .env
       echo DB_PASSWORD = ${{ secrets.DB_PASSWORD }} >> .env
       echo JWT_SECRET_KEY = ${{ secrets.JWT_SECRET_KEY }} >> .env
       echo API_TOKEN = ${{ secrets.API_TOKEN }} >> .env
       echo USER = ${{ secrets.USER }} >> .env
       echo PASSWORD = ${{ secrets.PASSWORD }} >> .env
       echo ACCOUNTID = ${{ secrets.ACCOUNTID }} >> .env
       npm install
       npx playwright test